CTL + A			SELECCIONA TODO
CTL + ENTER		EJECUTA SELECCIÓN
CTL + ESPACIO	AUTOCOMPLETAR
CTL + F7		DA FORMATO AL CÓDIGO
CTL + SHIFT +D 	BORRA CUADRO DE CONSULTAS
CTL + R 		REFRESCAR
ALT + FLECHA	NAVERGAR ENTRE PESTAÑAS