-- USER
DECLARE
    usuario VARCHAR2(40);
BEGIN
    usuario := USER();
    dbms_output.put_line(usuario);
END;

-- BUSCAR EN MI USUARIO MIS OBJETOS
SELECT * FROM USER_OBJECTS
WHERE OBJECT_TYPE='PROCEDURE';


-- SABER TODO DE MI USUARIO EN LA DB
SELECT OBJECT_TYPE, COUNT(*) FROM USER_OBJECTS
GROUP BY OBJECT_TYPE;

-- VER CÓDIGO FUENTE DE MIS OBJETOS
SELECT * FROM USER_SOURCE
WHERE NAME='MI_PROCEDIMIENTO';