-- CREANDO MI FUNCIÓN

DECLARE
    v_r NUMBER;
BEGIN
    v_r := FUNCTION1(100,30);
    DBMS_OUTPUT.PUT_LINE(v_r);
END;

-- USANDO FUNCIONES EN SQL


SELECT FIRST_NAME, SALARY, function1(EMPLOYEE_ID, 10) AS UWU FROM EMPLOYEES;
-- REQUERIMIENTOS
/*
    LA FUNCIÓN DEBE TENER UNICAMENTE DATOS IN
    DEBE ESTAR EN LA DB
    DEVUELVE UN DATO SQL
*/

-- PROCEDIMIENTO

CREATE OR REPLACE FUNCTION FUNCTION1 
(p_id EMPLOYEES.EMPLOYEE_ID%TYPE, p_impuesto_p NUMBER)
RETURN NUMBER
AS
    v_salario EMPLOYEES.SALARY%TYPE;
    v_imp NUMBER;
    E1 EXCEPTION;
BEGIN
    -- VALIDACIÓN DE DATOS ACEPTADOS
    IF p_impuesto_p>60 OR p_impuesto_p<0 THEN
        RAISE E1;
    END IF;
    -- CALCULANDO DATOS NECESARIOS
    SELECT SALARY
    INTO v_salario
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID=p_id;
    v_imp := v_salario*p_impuesto_p/100;
    --DBMS_OUTPUT.PUT_LINE(v_salario);
    --DBMS_OUTPUT.PUT_LINE(v_imp);
    RETURN v_imp;
EXCEPTION
    WHEN E1 THEN
        DBMS_OUTPUT.PUT_LINE('NO JALA EN EL RANGO DE IMPUESTOS ACEPTADOS');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR NO DEFINIDO: '||SQLCODE||' --> '||SQLERRM);  
END FUNCTION1 ;