-- JUGANDO CON ROWTYPE

CREATE TABLE REGIONES AS SELECT * FROM REGIONS WHERE REGION_ID=0; 

--ROBANDOME UNA FILA DE REGIONS A REGIONES
DECLARE
    v_miregion REGIONS%ROWTYPE;
BEGIN
    SELECT *
    INTO v_miregion
    FROM REGIONS
    WHERE REGION_ID=1;
    
    -- NOTESE QUE SE AGREGA LA VARIABLE QUE CONTIENE TODO
    INSERT INTO REGIONES 
    VALUES v_miregion;
END;


DECLARE
    v_miregion REGIONS%ROWTYPE;
BEGIN
    v_miregion.REGION_ID:=100;
    v_miregion.REGION_NAME:='UWU';
    
    UPDATE REGIONES 
    SET ROW=v_miregion 
    WHERE region_id=1;
END;
